### ISSUE TITLE
Cross-compilation support

### ISSUE THREAD

**Issue by daxpedda** [Manishearth/compiletest-rs#283]
I was trying to use `compiletest` to test code in different targets then the host target, e.g. in this case.
In this case run-support is not required, I just want to get compilation errors.

```rust
#[test]
fn test() {
	let config = Config {
		mode: Mode::CompileFail,
		src_base: PathBuf::from("tests/compile-fail"),
		target_rustcflags: Some(String::from(
			" -L target/wasm32-unknown-unknown/debug/deps --target wasm32-unknown-unknown",
		)),
		target: String::from("wasm32-unknown-unknown"),
		..Config::default()
	};

	config.clean_rlib();
	config.clean_rmeta();

	compiletest_rs::run_tests(&config);
}
```

```rust
extern crate test_crate_a;

compile_error!("test");
//~^ ERROR test

fn main() {}
```

Which doesn't seem to register any error:
```
error: tests/compile-fail/test.rs:3: expected error not found: test

error: 0 unexpected errors found, 1 expected errors not found
status: exit status: 1
command: "rustc" "tests/compile-fail/test.rs" "-L" "/tmp" "--target=wasm32-unknown-unknown" "--error-format" "json" "-o" "/tmp/test.stage-id.wasm" "-A" "unused" "-L" "target/wasm32-unknown-unknown/debug/deps" "--target" "wasm32-unknown-unknown" "-L" "/tmp/test.stage-id.aux"
not found errors (from test file): [
    Error {
        line_num: 3,
        kind: Some(
            Error,
        ),
        msg: "test",
    },
]
```

Apparently if I don't pass `--target wasm32-unknown-unknown` into `target_rustcflags` things work correctly, but I won't be able to import any dependencies:
```
command: "rustc" "tests/compile-fail/test.rs" "-L" "/tmp" "--target=wasm32-unknown-unknown" "--error-format" "json" "-o" "/tmp/test.stage-id.wasm" "-A" "unused" "-L" "target/wasm32-unknown-unknown/debug/deps" "-L" "/tmp/test.stage-id.aux"
unexpected errors (from JSON output): [
    Error {
        line_num: 1,
        kind: Some(
            Error,
        ),
        msg: "1:1: 1:25: can't find crate for `web_thread` [E0463]",
    },
]
```

Let me know if it's easier to set up a test repo.

**Comment by Manishearth** [comment]
You should check rustc for how it tests cross compilation.

In general this crate is in maintenance mode; it's not being used by clippy anymore and it's mostly a trailing fork of the rustc code. I don't think I can review or land major features.

**Comment by daxpedda** [comment]
> You should check rustc for how it tests cross compilation.

I know it should be possible because I manage to do it with `-Zdoctest-xcompile`, unfortunately I couldn't figure out what Rust does differently here.

> In general this crate is in maintenance mode; it's not being used by clippy anymore and it's mostly a trailing fork of the rustc code. I don't think I can review or land major features.

I wasn't aware, thank you for pointing this out!
In the meantime I have switched to [`ui_test`](https://crates.io/crates/ui_test) but encountered the same issue, so I will open one there.
